# Generated by Django 4.2.7 on 2023-11-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('director', models.CharField(max_length=100, verbose_name='Nombre')),
                ('release_date', models.DateField(default=None, null=True, verbose_name='Fecha de inicio')),
                ('banner', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
            ],
        ),
    ]
